#Because this file is named "application.*", the properties set within apply to all clients of the Config server. 
#This is great for us as we want all clients to find the Eureka server.
---
eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8010/eureka,http://eureka-primary:8011/eureka/,http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/
      #defaultZone: http://localhost:8010/eureka
      defaultZone: http://eureka-server:8010/eureka
---
spring:
  profiles: subject
words: I,You,He,She,It
  port: 8002
---
spring:
  profiles: verb
words: ran,knew,had,saw,bought
  port: 8003
---
spring:
  profiles: article
words: a,the
  port: 8004
---
spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely
  port: 8005
---
spring:
  profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog
  port: 8006
